const fs = require('fs')
const stringSimilarity = require("string-similarity");
const textproList = JSON.parse(fs.readFileSync('./lib/scraper/textproList.json'))
const { textpro } = require('../lib/scraper/textprome')

const listMaker = ["lightglow","retro","christmascandy","giraffe","arcane","countryflag","neonlight","deepsea","merrychristmas","Neonglitch","ColorLED","HappyNewYear","BATMAN","goldenancient","glowingneon","christmas","Christmastree","Thor","Halloween","rainbowcolor","cinematichorror","Americanflag","metallic","transformer","waterpipe","bluecircuit","berry","glossymetalic","CaptainAmerica","Halloweenskeleton","Videogameclassic","greenhorror","space","sketch","thunder","sci-fi","layered","artpapercut","embossed","neonlight","Brokenglass","gradient","foggywindow","HarryPotter","papercut","impressiveglitch","glossymetal","sciencefiction","glitch","watercolor","graffiti","underwater","coolwallgraffiti","cloud","SandSummerBeach","neondevil","bearmascot","magmahot","stonecracked","graffitiart","realisticbeach","realisticvintage","snow","Blackpink","gradient","realisticcloud","luxurygold","cloud","SandWriting","neon","christmasholiday","GlitchTikTok","MetalDarkGold","space","Pornhub","glue","summerysandwriting","NeonGalaxy","Holographic","Stone","RetroNeon","FoilBalloon","Marvelstudios","1917","DoubleExposure","Sandengraved","Avengers","Minion","GlossyCarbon","MetalPurple","DeluxeSilver","LuxuryMetal","Marvelstudios","NewYearCards","Happnewyearcardfirework","BlueMetal","Fabric","avatargold","FullcolorBalloon","DeluxeGold","MetalGalaxy","3DMetal","3DMetalSilver","3DMetalRoseGold","NeonEffect","XmasCards","HalloweenFire","Joker","MetalDarkGold","WolfLogoGalaxy","NinjaLogo","GreenFoilBalloon","Skeleton","NaturalLeaves","Wicker","CyanFoilBalloon","BloodGlass","PurpleFoilBalloon","WolfLogoBlackWhite","3DMetalGold","PinkFoilBalloon","BlueFoilBalloon","LionMascot","RedFoilBalloon","FireworkSparkle","Denim","Rock","Steel","PeridotStone","BlueGlass","Lava","YellowGlass","UltraGloss","GreenGlass","DecorateGreen","OrangeGlass","DecoratePurple","PurpleShiny","PurpleGlass","CyanGlass","GoldFoilBalloon","RedGlass","CaptainAmerica","RainbowEqualizer","PurpleGlass","Bread","PinkSparklingJewelry","Matrix","KoiFish","GoldSparklingJewelry","RobotR2D2","Strawberry","BlueSparklingJewelry","PurpleSparklingJewelry","CyanSparklingJewelry","Toxic","GreenSparklingJewelry","DecorativeGlass","HorrorBlood","ChocolateCake","RedSparklingJewelry","3DSteel","ChrismastGift","Thunder","FreeAdvancedGlow","Honey","GreenNeon","Dropwater","Marble","3DBox","RoadWarning","NeonTextEffect","Ice Cold","Bokeh","MarbleSlabs","NeonLight","BreakWall","HorrorGift","PlasticBagDrug","SCI-Fi","Wood","FruitJuice","BlueJewelry","PurpleGem","OrangeJewelry","RustyMetal","YellowJewelry","MetalRainbow","RedJewelry","Bagel","CyanJewelry","AbstraGold","PurpleJewelry","SilverJewelry","Biscuit","GreenJewelry"]

const list = ["lightglow","retro","christmascandy","giraffe","arcane","countryflag","neonlight","deepsea","merrychristmas","neonglitch","colorled","happynewyear","batman","goldenancient","glowingneon","christmas","christmastree","thor","halloween","rainbowcolor","cinematichorror","americanflag","metallic","transformer","waterpipe","bluecircuit","berry","glossymetalic","captainamerica","halloweenskeleton","videogameclassic","greenhorror","space","sketch","thunder","sci-fi","layered","artpapercut","embossed","neonlight","brokenglass","gradient","foggywindow","harrypotter","papercut","impressiveglitch","glossymetal","sciencefiction","glitch","watercolor","graffiti","underwater","coolwallgraffiti","cloud","sandsummerbeach","neondevil","bearmascot","magmahot","stonecracked","graffitiart","realisticbeach","realisticvintage","snow","blackpink","gradient","realisticcloud","luxurygold","cloud","sandwriting","neon","christmasholiday","glitchtiktok","metaldarkgold","space","pornhub","glue","summerysandwriting","neongalaxy","holographic","stone","retroneon","foilballoon","marvelstudios","1917","doubleexposure","sandengraved","avengers","minion","glossycarbon","metalpurple","deluxesilver","luxurymetal","marvelstudios","newyearcards","happnewyearcardfirework","bluemetal","fabric","avatargold","fullcolorballoon","deluxegold","metalgalaxy","3dmetal","3dmetalsilver","3dmetalrosegold","neoneffect","xmascards","halloweenfire","joker","metaldarkgold","wolflogogalaxy","ninjalogo","greenfoilballoon","skeleton","naturalleaves","wicker","cyanfoilballoon","bloodglass","purplefoilballoon","wolflogoblackwhite","3dmetalgold","pinkfoilballoon","bluefoilballoon","lionmascot","redfoilballoon","fireworksparkle","denim","rock","steel","peridotstone","blueglass","lava","yellowGlass","ultragloss","greenglass","decorategreen","orangeglass","decoratepurple","purpleshiny","purpleglass","cyanglass","goldfoilalloon","redglass","captainamerica","rainbowequalizer","purpleglass","bread","pinksparklingjewelry","matrix","koifish","goldsparklingewelry","robotr2d2","strawberry","bluesparklingjewelry","purpledparklingjewelry","cyansparklingjewelry","toxic","greensparklingjewelry","decorativeglass","horrorblood","chocolatecake","redsparklingjewelry","3dsteel","chrismastgift","thunder","freesdvancedglow","honey","greenneon","dropwater","marble","3dbox","roadwarning","neontexteffect","icecold","bokeh","marbleslabs","neonlight","breakwall","horrorgift","plasticbagdrug","sci-fi","wood","fruitJuice","blueJewelry","purplegem","orangejewelry","rustmetal","yellowjewelry","metalrainbow","redjewelry","bagel","cyanjewelry","abstraGlgold","purplejewelry","silverjewelry","biscuit","greenjewelry"]


module.exports = {
      CmD: list,
      aliases: list,
      categori: "zzimage maker",
      exec: async(m, { bob, text, args, command, prefix, quoted, budy }) => {     
      var matches = stringSimilarity.findBestMatch(command, listMaker);   
      const effect = matches.bestMatch.target;                
      const cari = textproList.find(({ title }) => title.toLowerCase() === effect.toLowerCase());     
      if (!cari) return bob.sendText(m.chat, `TextPro "${command}" not found`, m);   
        const params = args;
    const { link, parameters, title } = cari;
      if (parameters.length > params.length) return bob.sendText(m.chat, `TextPro "${command}" requires ${parameters.length} parameters, but ${params.length} given`, m);       
      m.reply('sedang di proses')
      const res = await textpro("https://textpro.me" + link, args)
      await bob.sendMessage(m.chat, { image: { url: res }, caption: `success create "${title}" text image` }, { quoted, m })
      }            
}      