const fs = require('fs')
const path = require('path')
const WW_PATH = path.join(__dirname, '..', 'assets', 'db', 'wwmaster.json')
global.werewolf = global.werewolf || {}
const sleep = (ms) => new Promise(r => setTimeout(r, ms))
const PM_DELAY_MS = 3000, RETRY_DELAY_MS = 4000
const NIGHT_TIMEOUT_SEC = 120, VOTE_TIMEOUT_SEC = 75
const LEADERBOARD_PATH = WW_PATH
function readLeaderboard(){ try{ if(!fs.existsSync(LEADERBOARD_PATH)) return []; let raw=fs.readFileSync(LEADERBOARD_PATH,'utf8').trim(); if(!raw) return []; return JSON.parse(raw)}catch(e){ return [] } }
function writeLeaderboard(d){ try{ fs.writeFileSync(LEADERBOARD_PATH, JSON.stringify(d,null,2)) }catch(e){} }
function updateLeaderboard(players,winner){ let data=readLeaderboard(); for(let p of players){ let entry=data.find(e=>e.jid===p.jid); if(!entry){ entry={jid:p.jid,name:p.jid.split('@')[0],games:0,wins:0,losses:0,asWerewolf:0,asVillager:0,winAsWerewolf:0,winAsVillager:0,kills:0,survived:0,winRate:'0%'}; data.push(entry) } let isW=p.role==='WEREWOLF', didWin=(isW&&winner==='WEREWOLF')||(!isW&&winner==='VILLAGE'); entry.games++; if(didWin) entry.wins++; else entry.losses++; if(isW){ entry.asWerewolf++; if(didWin) entry.winAsWerewolf++ } else { entry.asVillager++; if(didWin) entry.winAsVillager++ } if(p.status==='ALIVE') entry.survived++; entry.winRate=entry.games>0?(((entry.wins/entry.games)*100).toFixed(1)+'%'):'0%' } data.sort((a,b)=>b.wins-a.wins||parseFloat(b.winRate)-parseFloat(a.winRate)); writeLeaderboard(data); return data }
function formatLeaderboard(topN=10){ let data=readLeaderboard(); if(!data.length) return '📋 Belum ada data leaderboard.'; let medals=['🥇','🥈','🥉']; let lines=data.slice(0,topN).map((e,i)=>{ let medal=medals[i]||`${i+1}.`; let wr=e.winRate; let role=e.asWerewolf>e.asVillager?'🐺':'👨‍🌾'; return `${medal} *@${e.name}* ${role}\n    🏆 ${e.wins}W/${e.losses}L | WR: ${wr} | ${e.games} game` }); return `🏆 *MASTER OF WEREWOLF* 🏆\n${'─'.repeat(28)}\n${lines.join('\n')}\n${'─'.repeat(28)}\n📊 Total pemain: *${data.length}*` }
function toUserJid(jid){ if(!jid) return jid; let n=jid.replace(/@.*$/,'').replace(/[^0-9]/g,''); if(n.startsWith('0')) n='62'+n.slice(1); if(n.length<10) return null; return jid.includes('@')?jid:jid+'@s.whatsapp.net' }
async function safeSend(conn,jid,payload,retries=3){ let nj=toUserJid(jid); for(let i=0;i<retries;i++){ try{ await conn.sendMessage(nj,payload); return true }catch(e){ if(i<retries-1) await sleep(Math.min(2000*Math.pow(2,i),10000)) } } return false }
async function safeSendGroup(conn,gid,payload){ try{ await conn.sendMessage(gid,payload); return true }catch(e){ return false } }
function checkWinCondition(room){ let wAlive=room.players.filter(p=>p.role==='WEREWOLF'&&p.status==='ALIVE').length, nvAlive=room.players.filter(p=>p.role!=='WEREWOLF'&&p.status==='ALIVE').length; if(wAlive===0) return 'VILLAGE'; if(wAlive>=nvAlive) return 'WEREWOLF'; return null }
function getRoleCount(t){ let ww=t<=6?1:t<=9?2:3, doctor=t>=5?1:0, hunter=t>=7?1:0, witch=t>=9?1:0, villager=Math.max(t-ww-1-doctor-hunter-witch,0); return {WEREWOLF:ww,SEER:1,DOCTOR:doctor,HUNTER:hunter,WITCH:witch,VILLAGER:villager} }
function roleEmoji(r){ return {WEREWOLF:'🐺',SEER:'🔮',DOCTOR:'💉',HUNTER:'🏹',WITCH:'🧙',VILLAGER:'👨‍🌾'}[r]||'❓' }
function roleDesc(r){ return {WEREWOLF:'Kamu adalah Werewolf! Setiap malam, bunuh satu warga desa.',SEER:'Kamu adalah Penerawang! Setiap malam, cek peran satu pemain.',DOCTOR:'Kamu adalah Dokter! Setiap malam, lindungi satu pemain.',HUNTER:'Kamu adalah Pemburu! Jika kamu mati kapanpun, kamu bisa menembak balik 1 pemain.',WITCH:'Kamu adalah Penyihir! Punya 1x ramuan hidup & 1x racun.',VILLAGER:'Kamu adalah Warga Desa. Gunakan diskusi untuk menemukan Werewolf!'}[r]||'' }
function buildPlayerList(players){ return players.map((p,i)=>`${i+1}. @${p.jid.split('@')[0]}${p.status==='DEAD'?' ☠️':''}`).join('\n') }
function toSections(rows,title='☰ Daftar Pemain'){ let s=[]; for(let i=0;i<rows.length;i+=10) s.push({title:i===0?title:`${title} ${i/10+1}`,rows:rows.slice(i,i+10)}); return s }
function nightPlayerRows(room,pfx,action,exclude=[]){ let rows=[]; room.players.forEach((p,i)=>{ if(p.status!=='ALIVE') return; if(exclude.includes(p.jid)) return; let num=p.jid.split('@')[0].slice(0,15); rows.push({title:`${i+1}. ${num}`,description:'Ketuk untuk memilih',id:`${pfx} ${action} ${i+1}`}) }); return rows }
function nightButtonsFor(room,player,pfx){ if(player.role==='WEREWOLF'){ let wwJids=room.players.filter(p=>p.role==='WEREWOLF').map(p=>p.jid); let rows=nightPlayerRows(room,pfx,'kill',[...wwJids,player.jid]); return rows.length?[{type:'list',title:'🔪 Pilih Korban',sections:toSections(rows)}]:[] } if(player.role==='SEER'){ let rows=nightPlayerRows(room,pfx,'terawang',[player.jid]); return rows.length?[{type:'list',title:'🔮 Terawang Siapa?',sections:toSections(rows)}]:[] } if(player.role==='DOCTOR'){ let rows=nightPlayerRows(room,pfx,'protect',room.nightAction.lastProtect?[room.nightAction.lastProtect]:[]); return rows.length?[{type:'list',title:'💉 Lindungi Siapa?',sections:toSections(rows)}]:[] } if(player.role==='WITCH'){ let btns=[]; if(room.witch.canSave&&room.nightAction.kills.length>0) btns.push({title:'✨ Save Korban',id:`${pfx} save`}); if(room.witch.canPoison){ let pr=nightPlayerRows(room,pfx,'poison',[player.jid]); if(pr.length) btns.push({type:'list',title:'☠️ Racuni Siapa?',sections:toSections(pr)}) } btns.push({title:'⏭️ Skip',id:`${pfx} skip`}); return btns } return [] }
function voteListButtons(room,pfx){ let rows=nightPlayerRows(room,pfx,'vote'); return rows.length?[{type:'list',title:'🗳️ Vote Eksekusi',sections:toSections(rows,'🗳️ Pilih Pemain')}]:[] }
function lobbyText(room,pfx){ let lines=room.players.map((p,i)=>`${i+1}. @${p.jid.split('@')[0]}`); let text=`🐺 *LOBBY WEREWOLF* 🐺\n👥 Pemain: *${room.players.length}* (min. 4)\n\n`+(lines.length?lines.join('\n'):'_Belum ada pemain._')+`\n\n➕ Gabung: *${pfx} join*\n🚪 Keluar: *${pfx} leave*\n▶️ Mulai (min. 4): *${pfx} start*`; return {text,mentions:room.players.map(p=>p.jid)} }
async function refreshLobby(room,conn,pfx){ const{ text,mentions }=lobbyText(room,pfx); if(room.lobbyKey){ try{ await conn.relayMessage(room.id,{protocolMessage:{key:room.lobbyKey,type:14,editedMessage:{extendedTextMessage:{text,contextInfo:{mentionedJid:mentions}}}}},{}); return true }catch(e){} } try{ const sent=await conn.sendMessage(room.id,{text,mentions}); if(sent?.key) room.lobbyKey=sent.key; return true }catch(e){ return false } }
async function sendWWButtons(conn,jid,text,buttons,opts={}){ try{ if(buttons&&buttons.length>0){ await conn.sendMessage(jid,{text,footer:opts.footer||'🐺 Ultimate Werewolf',buttons,headerType:1,viewOnce:true},{quoted:opts.quoted}); return true } throw new Error('no') }catch(e){ try{ await conn.sendMessage(jid,{text,...(opts.mentions?{mentions:opts.mentions}:{})},opts.quoted?{quoted:opts.quoted}:{}); return true }catch(e2){ return false } } }
function freshNightAction(prev=null){ return {kills:[],seer:null,protect:null,save:false,poison:null,witchDone:false,lastProtect:prev} }
function startNightTimer(room,conn){ clearNightTimer(room); const WARN=30; room._nightWarnTimeout=setTimeout(async()=>{ if(room.state!=='NIGHT') return; let pending=getNightPending(room); if(!pending.length) return; await safeSendGroup(conn,room.id,{text:`⚠️ *[MALAM]* Sisa *${WARN} detik!*\nMasih ada *${pending.length}* pemain belum beraksi.`}); for(let p of pending){ await sleep(500); await safeSend(conn,p.jid,{text:`⚠️ *[MALAM - ${room.round}]* Sisa *${WARN} detik*, segera beraksi!`}) } },(NIGHT_TIMEOUT_SEC-WARN)*1000); room._nightTimeout=setTimeout(async()=>{ if(room.state!=='NIGHT') return; let pending=getNightPending(room); if(!pending.length) return; let wwAlive=room.players.some(p=>p.role==='WEREWOLF'&&p.status==='ALIVE'), seerAlive=room.players.some(p=>p.role==='SEER'&&p.status==='ALIVE'), docAlive=room.players.some(p=>p.role==='DOCTOR'&&p.status==='ALIVE'), witchAlive=room.players.some(p=>p.role==='WITCH'&&p.status==='ALIVE'); if(wwAlive&&room.nightAction.kills.length===0){ let c=room.players.filter(p=>p.role!=='WEREWOLF'&&p.status==='ALIVE'); if(c.length) room.nightAction.kills.push(c[Math.floor(Math.random()*c.length)].jid); else room.nightAction.kills.push('__none__') } if(seerAlive&&room.nightAction.seer===null) room.nightAction.seer='__skip__'; if(docAlive&&room.nightAction.protect===null) room.nightAction.protect='__skip__'; if(witchAlive&&!room.nightAction.witchDone) room.nightAction.witchDone=true; await safeSendGroup(conn,room.id,{text:`⏰ *WAKTU MALAM HABIS!* ${pending.length} pemain di-skip.`}); for(let p of pending){ await sleep(500); await safeSend(conn,p.jid,{text:`⏰ *[MALAM HABIS]* Kamu di-skip.`}) } if(room.nightAction.kills[0]==='__none__') room.nightAction.kills=[]; await resolveNight(room,conn) },NIGHT_TIMEOUT_SEC*1000) }
function clearNightTimer(room){ if(room._nightTimeout) {clearTimeout(room._nightTimeout); room._nightTimeout=null} if(room._nightWarnTimeout){clearTimeout(room._nightWarnTimeout); room._nightWarnTimeout=null} }
function getNightPending(room){ let pending=[], ww=room.players.filter(p=>p.role==='WEREWOLF'&&p.status==='ALIVE'), se=room.players.filter(p=>p.role==='SEER'&&p.status==='ALIVE'), doc=room.players.filter(p=>p.role==='DOCTOR'&&p.status==='ALIVE'), wi=room.players.filter(p=>p.role==='WITCH'&&p.status==='ALIVE'); if(ww.length&&room.nightAction.kills.length===0) pending.push(...ww); if(se.length&&room.nightAction.seer===null) pending.push(...se); if(doc.length&&room.nightAction.protect===null) pending.push(...doc); if(wi.length&&!room.nightAction.witchDone) pending.push(...wi); return pending }
async function sendVoteSummary(room,conn){ let alive=room.players.filter(p=>p.status==='ALIVE'), voted=Object.keys(room.votes), notVoted=alive.filter(p=>!room.votes[p.jid]), tally={}; for(let[,t] of Object.entries(room.votes)) tally[t]=(tally[t]||0)+1; let msg=`📊 *STATUS VOTE* (${voted.length}/${alive.length})\n\n`; if(Object.keys(tally).length){ msg+=`🗳️ *Perolehan:*\n`; let s=Object.entries(tally).sort((a,b)=>b[1]-a[1]); for(let[j,c] of s) msg+=`@${j.split('@')[0]}: ${'⭐'.repeat(c)} (${c})\n`; msg+='\n' } if(voted.length){ msg+=`✅ *Sudah vote:*\n`; for(let[v,t] of Object.entries(room.votes)) msg+=`• @${v.split('@')[0]} → @${t.split('@')[0]}\n`; msg+='\n' } if(notVoted.length) msg+=`⏳ *Belum vote:*\n`+notVoted.map(p=>`• @${p.jid.split('@')[0]}`).join('\n'); else msg+=`✅ *Semua sudah vote!*`; let all=[...voted,...Object.values(room.votes),...notVoted.map(p=>p.jid)]; await safeSendGroup(conn,room.id,{text:msg,mentions:[...new Set(all)]}) }
function startVoteTimer(room,conn){ clearVoteTimer(room); const WARN=30; room._voteWarnTimeout=setTimeout(async()=>{ if(room.state!=='DAY') return; let alive=room.players.filter(p=>p.status==='ALIVE'), not=alive.filter(p=>!room.votes[p.jid]); if(!not.length) return; await safeSendGroup(conn,room.id,{text:`⚠️ *[VOTING]* Sisa *${WARN} detik!*\n`+not.map(p=>`• @${p.jid.split('@')[0]}`).join('\n'),mentions:not.map(p=>p.jid)}); for(let p of not){ await sleep(500); await safeSend(conn,p.jid,{text:`⚠️ *[VOTING - ${room.round}]* Sisa ${WARN} detik, segera vote!`}) } },(VOTE_TIMEOUT_SEC-WARN)*1000); room._voteTimeout=setTimeout(async()=>{ if(room.state!=='DAY') return; let alive=room.players.filter(p=>p.status==='ALIVE'), not=alive.filter(p=>!room.votes[p.jid]); if(!not.length) return; await safeSendGroup(conn,room.id,{text:`⏰ *WAKTU VOTING HABIS!* ${not.length} abstain`,mentions:not.map(p=>p.jid)}); await resolveVote(room,conn) },VOTE_TIMEOUT_SEC*1000) }
function clearVoteTimer(room){ if(room._voteTimeout) {clearTimeout(room._voteTimeout); room._voteTimeout=null} if(room._voteWarnTimeout){clearTimeout(room._voteWarnTimeout); room._voteWarnTimeout=null} }
async function endGame(room,conn,winner,finalMsg){
    let lb=updateLeaderboard(room.players,winner);
    let medals=['🥇','🥈','🥉'], top3=lb.slice(0,3).map((e,i)=>`${medals[i]} @${e.name} — ${e.wins}W | WR ${e.winRate}`).join('\n');
    // Economy reward untuk pemenang
    try {
        const economy = require('./economy');
        const winners = room.players.filter(p=>{
            const isW = p.role==='WEREWOLF';
            return (isW && winner==='WEREWOLF') || (!isW && winner==='VILLAGE');
        });
        for (const w of winners) {
            try { await economy.giveGameReward(w.jid, 'werewolf_win', { idempotency: `ww_${room.id}_${room.round}` }) } catch {}
        }
        // tambahkan info reward ke pesan akhir
        finalMsg += `\n\n💰 Pemenang +Rp ${economy.formatMoney(600)}~Rp ${economy.formatMoney(900)} Money!`
    } catch {}
    let full=finalMsg+`\n\n🏆 *TOP 3*\n`+top3; await safeSendGroup(conn,room.id,{text:full,mentions:room.players.map(p=>p.jid)}); clearNightTimer(room); clearVoteTimer(room); delete global.werewolf[room.id] }
async function resolveVote(room,conn){ clearVoteTimer(room); if(!Object.keys(room.votes).length){ let msg=`🤷 *Tidak ada yang vote!*\n\n🌙 *MALAM TIBA...* ⏰ ${NIGHT_TIMEOUT_SEC} detik`; await safeSendGroup(conn,room.id,{text:msg,mentions:room.players.map(p=>p.jid)}); let prev=room.nightAction.protect; room.round++; room.nightAction=freshNightAction(prev); room.votes={}; await startNight(room,conn); return } let tally={}; for(let v of Object.values(room.votes)) tally[v]=(tally[v]||0)+1; let max=0,cands=[]; for(let[j,c] of Object.entries(tally)){ if(c>max){max=c;cands=[j]} else if(c===max) cands.push(j) } let execMsg=`🔥 *HASIL VOTING* 🔥\n\n📊 *Rekap:*\n`; let s=Object.entries(tally).sort((a,b)=>b[1]-a[1]); for(let[j,c] of s) execMsg+=`  @${j.split('@')[0]}: ${'⭐'.repeat(c)} (${c})\n`; execMsg+='\n'; if(cands.length>1){ execMsg+=`⚖️ *SERI!* Tidak ada yang dieksekusi.\n\n🌙 *MALAM TIBA...* ⏰ ${NIGHT_TIMEOUT_SEC} detik`; let prev=room.nightAction.protect; room.round++; room.nightAction=freshNightAction(prev); room.votes={}; await safeSendGroup(conn,room.id,{text:execMsg,mentions:room.players.map(p=>p.jid)}); await startNight(room,conn); return } let execJid=cands[0], execPlayer=room.players.find(p=>p.jid===execJid); execPlayer.status='DEAD'; execMsg+=`☠️ *@${execJid.split('@')[0]}* dieksekusi (${max} suara)\nPeran: *${roleEmoji(execPlayer.role)} ${execPlayer.role}*\n\n`; if(execPlayer.role==='HUNTER') room.hunterPending=execJid; let win=checkWinCondition(room); if(win){ execMsg+=win==='VILLAGE'?`🎉 *WARGA MENANG!*`:`🐺 *WEREWOLF MENANG!*`; execMsg+=`\n\n*Peran:*\n`+room.players.map((p,i)=>`${i+1}. @${p.jid.split('@')[0]} → ${roleEmoji(p.role)} ${p.role}`).join('\n'); await endGame(room,conn,win,execMsg); return } if(room.hunterPending){ execMsg+=`🏹 *HUNTER TEWAS!* @${execPlayer.jid.split('@')[0]} boleh menembak!`; await safeSendGroup(conn,room.id,{text:execMsg,mentions:room.players.map(p=>p.jid)}); await sleep(1000); let _pfx=room.pfx||'.ww', rows=nightPlayerRows(room,_pfx,'shoot',[room.hunterPending]); await sendWWButtons(conn,room.hunterPending,`🏹 Kamu dieksekusi! Pilih target:\n\n${buildPlayerList(room.players)}`,rows.length?[{type:'list',title:'🏹 Tembak?',sections:toSections(rows)}]:[]); room.state='HUNTER'; return } let prev=room.nightAction.protect; room.round++; room.nightAction=freshNightAction(prev); room.votes={}; execMsg+=`🌙 *MALAM TIBA...* ⏰ ${NIGHT_TIMEOUT_SEC} detik`; await safeSendGroup(conn,room.id,{text:execMsg,mentions:room.players.map(p=>p.jid)}); await startNight(room,conn) }
async function checkNightComplete(room,conn){ let wwAlive=room.players.some(p=>p.role==='WEREWOLF'&&p.status==='ALIVE'), seAlive=room.players.some(p=>p.role==='SEER'&&p.status==='ALIVE'), docAlive=room.players.some(p=>p.role==='DOCTOR'&&p.status==='ALIVE'), wiAlive=room.players.some(p=>p.role==='WITCH'&&p.status==='ALIVE'); let wwDone=!wwAlive||room.nightAction.kills.length>0, seDone=!seAlive||room.nightAction.seer!==null, docDone=!docAlive||room.nightAction.protect!==null, wiDone=!wiAlive||room.nightAction.witchDone===true; if(wwDone&&seDone&&docDone&&wiDone){ clearNightTimer(room); await resolveNight(room,conn) } }
async function startNight(room,conn){ room.state='NIGHT'; room.votes={}; let alive=room.players.filter(p=>p.status==='ALIVE'), plist=buildPlayerList(room.players), wwJids=room.players.filter(p=>p.role==='WEREWOLF'&&p.status==='ALIVE').map(p=>p.jid); for(let i=0;i<alive.length;i++){ let p=alive[i]; if(i>0) await sleep(1500); let msg=`🌙 *MALAM - PUTARAN ${room.round}*\n⏰ ${NIGHT_TIMEOUT_SEC} detik\n\n`; if(p.role==='WEREWOLF'){ let partners=wwJids.filter(j=>j!==p.jid); if(partners.length) msg+=`🐺 Rekan: ${partners.map(j=>'@'+j.split('@')[0]).join(', ')}\n\n`; msg+=`*.ww kill <nomor>*\n\n` } else if(p.role==='SEER') msg+=`*.ww terawang <nomor>*\n\n`; else if(p.role==='DOCTOR') msg+=`*.ww protect <nomor>*\n\n`; else if(p.role==='WITCH') msg+=`*.ww save / poison / skip*\n\n`; else msg+=`😴 Tidur desa\n\n`; msg+=`*Daftar:*\n${plist}`; await sendWWButtons(conn,p.jid,msg,nightButtonsFor(room,p,room.pfx||'.ww')) } startNightTimer(room,conn) }
async function resolveNight(room,conn){ clearNightTimer(room); room.state='DAY'; let victimJid=room.nightAction.kills[0]||null; if(room.nightAction.seer==='__skip__') room.nightAction.seer=null; if(room.nightAction.protect==='__skip__') room.nightAction.protect=null; let saved=false; if(victimJid&&room.nightAction.protect===victimJid){ saved=true; victimJid=null } if(victimJid&&room.nightAction.save&&room.witch.canSave){ saved=true; victimJid=null; room.witch.canSave=false } let morning=`☀️ *PAGI - ${room.round}* ☀️\n\n`; if(victimJid){ let vic=room.players.find(p=>p.jid===victimJid); if(vic){ vic.status='DEAD'; morning+=`😱 Mayat *@${vic.jid.split('@')[0]}* (${roleEmoji(vic.role)} ${vic.role})\n\n`; if(vic.role==='HUNTER') room.hunterPending=victimJid } } else if(saved) morning+=`🍀 Semua selamat!\n\n`; else morning+=`🌅 Tanpa insiden.\n\n`; if(room.nightAction.poison&&room.witch.canPoison){ let poi=room.players.find(p=>p.jid===room.nightAction.poison); if(poi&&poi.status==='ALIVE'){ poi.status='DEAD'; room.witch.canPoison=false; morning+=`💀 Racun: *@${poi.jid.split('@')[0]}* (${roleEmoji(poi.role)} ${poi.role})\n\n`; if(poi.role==='HUNTER') room.hunterPending=poi.jid } } let prev=room.nightAction.protect; let win=checkWinCondition(room); if(win){ morning+=win==='VILLAGE'?`🎉 *WARGA MENANG!*`:`🐺 *WEREWOLF MENANG!*`; morning+=`\n\n*Peran:*\n`+room.players.map((p,i)=>`${i+1}. @${p.jid.split('@')[0]} → ${roleEmoji(p.role)} ${p.role}`).join('\n'); await endGame(room,conn,win,morning); return } if(room.hunterPending){ let h=room.players.find(p=>p.jid===room.hunterPending); morning+=`🏹 *HUNTER* @${h.jid.split('@')[0]} boleh menembak!`; await safeSendGroup(conn,room.id,{text:morning,mentions:room.players.map(p=>p.jid)}); await sleep(1000); let _pfx=room.pfx||'.ww', rows=nightPlayerRows(room,_pfx,'shoot',[room.hunterPending]); await sendWWButtons(conn,room.hunterPending,`🏹 Pilih target:\n\n${buildPlayerList(room.players)}`,rows.length?[{type:'list',title:'🏹 Tembak?',sections:toSections(rows)}]:[]); room.state='HUNTER'; room.nightAction=freshNightAction(prev); return } let alive=room.players.filter(p=>p.status==='ALIVE'); morning+=`👥 *Hidup (${alive.length}):*\n`; room.players.forEach((p,i)=>{ if(p.status==='ALIVE') morning+=`${i+1}. @${p.jid.split('@')[0]}\n`}); morning+=`\nVote: *.ww vote <nomor>* ⏰ ${VOTE_TIMEOUT_SEC} detik`; await safeSendGroup(conn,room.id,{text:morning,mentions:room.players.map(p=>p.jid)}); room.nightAction=freshNightAction(prev); room.votes={}; startVoteTimer(room,conn) }

async function handle(m, conn, ctx){
    let { args, prefix, command } = ctx
    let pfx = prefix + command
    let room = m.isGroup ? global.werewolf[m.chat] : Object.values(global.werewolf).find(r=>r.players.some(p=>p.jid===m.sender))
    let action = (args[0]||'').toLowerCase()
    if(room) room.pfx=pfx
    const reply = (t)=> conn.sendMessage(m.chat,{text:t},{quoted:m})
    // Game werewolf hanya dimainkan di dalam grup. Aksi malam (kill,
    // terawang, protect, save, poison, skip, shoot) tetap via PM agar
    // peran rahasia tidak bocor — sisanya wajib di grup.
    const PM_ACTIONS = new Set(['kill','terawang','protect','save','poison','skip','shoot'])
    if (!m.isGroup && !PM_ACTIONS.has(action)) {
        return reply(`❌ Game werewolf hanya bisa dimainkan di dalam grup!\nBuat lobi dulu di grup: ${pfx} create`)
    }
    if(!action || action==='help'){
        return conn.sendMessage(m.chat,{text:`🐺 *WEREWOLF* 🐺\nRoles: 🐺 🔮 💉 🏹 🧙 👨‍🌾\nMalam ${NIGHT_TIMEOUT_SEC}s | Vote ${VOTE_TIMEOUT_SEC}s\n\n${pfx} create | join | leave | start | info | votes | leaderboard | stats | stop\nContoh: ${pfx} create`},{quoted:m})
    }
    if(action==='leaderboard'||action==='lb'||action==='rank'){ let topN=parseInt(args[1])||10, text=formatLeaderboard(topN), data=readLeaderboard(), mentions=data.slice(0,topN).map(e=>e.jid).filter(Boolean); return conn.sendMessage(m.chat,{text,mentions},{quoted:m}) }
    if(action==='stats'){ let data=readLeaderboard(), e=data.find(x=>x.jid===m.sender); if(!e) return reply('❌ Belum punya data'); let rank=data.findIndex(x=>x.jid===m.sender)+1; return reply(`📊 *STAT KAMU* #${rank}\n👤 @${e.name}\n🎮 ${e.games} game | 🏆 ${e.wins}W/${e.losses}L | WR ${e.winRate}\n🐺 WW ${e.asWerewolf} (${e.winAsWerewolf}W) | 👨‍🌾 ${e.asVillager} (${e.winAsVillager}W)`) }
    if(action==='create'){ if(!m.isGroup) return reply('❌ Hanya di grup!'); if(room) return reply('⚠️ Sudah ada sesi!'); global.werewolf[m.chat]={id:m.chat,state:'LOBBY',host:m.sender,players:[],votes:{},round:0,hunterPending:null,witch:{canSave:true,canPoison:true},nightAction:freshNightAction(),lobbyKey:null,_nightTimeout:null,_nightWarnTimeout:null,_voteTimeout:null,_voteWarnTimeout:null}; await refreshLobby(global.werewolf[m.chat],conn,pfx); return }
    if(action==='join'){ if(!m.isGroup) return reply('❌ Hanya di grup!'); if(!room) return reply(`Belum ada lobi, ${pfx} create`); if(room.state!=='LOBBY') return reply('🚫 Sudah dimulai'); if(room.players.find(p=>p.jid===m.sender)) return reply('✅ Sudah di lobi'); room.players.push({jid:m.sender,role:null,status:'ALIVE'}); await refreshLobby(room,conn,pfx); return }
    if(action==='leave'){ if(!m.isGroup) return reply('❌ Hanya di grup!'); if(!room||room.state!=='LOBBY') return reply('🚫 Tidak bisa keluar'); let idx=room.players.findIndex(p=>p.jid===m.sender); if(idx===-1) return reply('❌ Tidak di lobi'); room.players.splice(idx,1); await refreshLobby(room,conn,pfx); return }
    if(action==='info'){ if(!room) return reply('⚠️ Tidak ada game'); let alive=room.players.filter(p=>p.status==='ALIVE').length, dead=room.players.filter(p=>p.status==='DEAD').length; return reply(`🐺 *INFO*\nFase ${room.state} | Ronde ${room.round}\nHidup ${alive} | Mati ${dead}\n\n${buildPlayerList(room.players)}`) }
    if(action==='votes'){ if(!m.isGroup) return reply('❌ Hanya di grup!'); if(!room) return reply('⚠️ Tidak ada game'); if(room.state!=='DAY') return reply('🚫 Voting hanya siang'); await sendVoteSummary(room,conn); return }
    if(action==='start'){
        if(!m.isGroup) return reply('❌ Hanya di grup!'); if(!room) return reply(`Belum ada lobi`); if(room.state!=='LOBBY') return reply('🚫 Sudah berjalan'); if(room.players.length<4) return reply(`Min 4, baru ${room.players.length}`);
        let total=room.players.length, rc=getRoleCount(total), pool=[]; for(let[r,c] of Object.entries(rc)) for(let i=0;i<c;i++) pool.push(r); for(let i=pool.length-1;i>0;i--){ let j=Math.floor(Math.random()*(i+1)); [pool[i],pool[j]]=[pool[j],pool[i]] }
        let shuffled=[...room.players].sort(()=>Math.random()-0.5); shuffled.forEach((p,i)=>{ room.players.find(x=>x.jid===p.jid).role=pool[i] })
        room.state='NIGHT'; room.round=1; room.hunterPending=null; room.witch={canSave:true,canPoison:true}; room.nightAction=freshNightAction(); room.votes={};
        try{ if(room.lobbyKey) await conn.relayMessage(room.id,{protocolMessage:{key:room.lobbyKey,type:14,editedMessage:{conversation:`🎭 *GAME DIMULAI!* ${total} pemain`}}},{}) }catch{}
        let rb=Object.entries(rc).filter(([,c])=>c>0).map(([r,c])=>`${roleEmoji(r)} ${r}:${c}`).join(' | '); await safeSendGroup(conn,m.chat,{text:`🎭 *GAME DIMULAI!* ${total} pemain\n${rb}\nCek PM untuk peran!`,mentions:room.players.map(p=>p.jid)}); let plist=buildPlayerList(room.players), wwJids=room.players.filter(p=>p.role==='WEREWOLF').map(p=>p.jid); for(let i=0;i<room.players.length;i++){ let p=room.players[i]; if(i>0) await sleep(PM_DELAY_MS); let msg=`🐺 *WEREWOLF* Putaran 1\n${roleEmoji(p.role)} *${p.role}*\n${roleDesc(p.role)}\n`; if(p.role==='WEREWOLF'&&wwJids.length>1){ let partners=wwJids.filter(j=>j!==p.jid); msg+=`\nRekan: ${partners.map(j=>'@'+j.split('@')[0]).join(', ')}\n` } msg+=`\n*Daftar:*\n${plist}\n\n`; if(p.role==='WEREWOLF') msg+=`*.ww kill <nomor>*`; else if(p.role==='SEER') msg+=`*.ww terawang <nomor>*`; else if(p.role==='DOCTOR') msg+=`*.ww protect <nomor>*`; else if(p.role==='WITCH') msg+=`*.ww save/poison/skip*`; else msg+=`😴 Tidur desa`; await sendWWButtons(conn,p.jid,msg,nightButtonsFor(room,p,pfx)) } startNightTimer(room,conn); return
    }
    if(action==='kill'){ if(m.isGroup) return reply('❌ Di PM!'); if(!room) return reply('⚠️ Tidak di game'); if(room.state!=='NIGHT') return reply('🚫 Bukan malam'); let me=room.players.find(p=>p.jid===m.sender); if(!me||me.role!=='WEREWOLF') return reply('❌ Bukan WW'); if(me.status==='DEAD') return reply('☠️ Mati'); if(room.nightAction.kills.length>0) return reply('✅ Sudah pilih'); let idx=parseInt(args[1])-1; if(isNaN(idx)||idx<0||idx>=room.players.length) return reply('❌ Nomor salah'); let t=room.players[idx]; if(!t||t.status==='DEAD') return reply('❌ Target mati'); if(t.jid===m.sender) return reply('❌ Tidak bunuh diri'); if(t.role==='WEREWOLF') return reply('❌ Sesama WW'); room.nightAction.kills.push(t.jid); await conn.sendMessage(m.chat,{text:`🔪 Memilih @${t.jid.split('@')[0]}`},{quoted:m}); let other=room.players.filter(p=>p.role==='WEREWOLF'&&p.status==='ALIVE'&&p.jid!==m.sender); for(let ww of other){ await sleep(500); await safeSend(conn,ww.jid,{text:`🐺 Rekan memilih @${t.jid.split('@')[0]}`,mentions:[t.jid]}) } await checkNightComplete(room,conn); return }
    if(action==='terawang'){ if(m.isGroup) return reply('❌ Di PM!'); if(!room) return reply('⚠️ Tidak di game'); if(room.state!=='NIGHT') return reply('🚫 Bukan malam'); let me=room.players.find(p=>p.jid===m.sender); if(!me||me.role!=='SEER') return reply('❌ Bukan Seer'); if(room.nightAction.seer!==null) return reply('✅ Sudah'); let idx=parseInt(args[1])-1; if(isNaN(idx)||idx<0||idx>=room.players.length) return reply('❌ Nomor salah'); let t=room.players[idx]; if(!t||t.status==='DEAD') return reply('❌ Target mati'); room.nightAction.seer=t.jid; await safeSend(conn,m.sender,{text:`🔮 @${t.jid.split('@')[0]} = *${roleEmoji(t.role)} ${t.role}*`,mentions:[t.jid]}); await checkNightComplete(room,conn); return }
    if(action==='protect'){ if(m.isGroup) return reply('❌ Di PM!'); if(!room) return reply('⚠️ Tidak di game'); if(room.state!=='NIGHT') return reply('🚫 Bukan malam'); let me=room.players.find(p=>p.jid===m.sender); if(!me||me.role!=='DOCTOR') return reply('❌ Bukan Dokter'); if(room.nightAction.protect!==null) return reply('✅ Sudah'); let idx=parseInt(args[1])-1; let t=room.players[idx]; if(!t||t.status==='DEAD') return reply('❌ Salah'); if(t.jid===room.nightAction.lastProtect) return reply('❌ Tidak boleh sama 2 malam'); room.nightAction.protect=t.jid; await reply(`💉 Melindungi @${t.jid.split('@')[0]}`); await checkNightComplete(room,conn); return }
    if(action==='save'){ if(m.isGroup) return reply('❌ Di PM!'); if(!room) return reply('⚠️ Tidak di game'); if(room.state!=='NIGHT') return reply('🚫 Bukan malam'); let me=room.players.find(p=>p.jid===m.sender); if(!me||me.role!=='WITCH') return reply('❌ Bukan Witch'); if(room.nightAction.witchDone) return reply('✅ Sudah'); if(!room.witch.canSave) return reply('❌ Habis'); if(!room.nightAction.kills.length) return reply('ℹ️ Belum ada korban'); room.nightAction.save=true; room.nightAction.witchDone=true; await reply('✨ Save!'); await checkNightComplete(room,conn); return }
    if(action==='poison'){ if(m.isGroup) return reply('❌ Di PM!'); if(!room) return reply('⚠️ Tidak di game'); if(room.state!=='NIGHT') return reply('🚫 Bukan malam'); let me=room.players.find(p=>p.jid===m.sender); if(!me||me.role!=='WITCH') return reply('❌ Bukan Witch'); if(room.nightAction.witchDone) return reply('✅ Sudah'); if(!room.witch.canPoison) return reply('❌ Habis'); let idx=parseInt(args[1])-1; let t=room.players[idx]; if(!t||t.status==='DEAD') return reply('❌ Salah'); room.nightAction.poison=t.jid; room.nightAction.witchDone=true; await reply(`☠️ Racun @${t.jid.split('@')[0]}`); await checkNightComplete(room,conn); return }
    if(action==='skip'){ if(m.isGroup) return reply('❌ Di PM!'); let me=room.players.find(p=>p.jid===m.sender); if(!me||me.role!=='WITCH') return reply('❌ Hanya Witch'); if(room.nightAction.witchDone) return reply('✅ Sudah'); room.nightAction.witchDone=true; await reply('⏭️ Skip'); await checkNightComplete(room,conn); return }
    if(action==='shoot'){ if(m.isGroup) return reply('❌ Di PM!'); if(!room||room.state!=='HUNTER') return reply('🚫 Bukan waktu Hunter'); let me=room.players.find(p=>p.jid===m.sender); if(!me||me.role!=='HUNTER'||room.hunterPending!==m.sender) return reply('❌ Bukan giliran'); let idx=parseInt(args[1])-1; let t=room.players[idx]; if(!t||t.status==='DEAD') return reply('❌ Salah'); t.status='DEAD'; room.hunterPending=null; let msg=`🏹 *@${m.sender.split('@')[0]}* menembak *@${t.jid.split('@')[0]}* (${roleEmoji(t.role)} ${t.role})`; let win=checkWinCondition(room); if(win){ msg+=win==='VILLAGE'?`\n🎉 WARGA MENANG`:`\n🐺 WEREWOLF MENANG`; msg+=`\n\n`+room.players.map((p,i)=>`${i+1}. @${p.jid.split('@')[0]} → ${roleEmoji(p.role)} ${p.role}`).join('\n'); await endGame(room,conn,win,msg); return } let alive=room.players.filter(p=>p.status==='ALIVE'); msg+=`\n\nHidup ${alive.length}: `+alive.map(p=>`@${p.jid.split('@')[0]}`).join(', '); room.state='DAY'; room.votes={}; await safeSendGroup(conn,room.id,{text:msg,mentions:room.players.map(p=>p.jid)}); startVoteTimer(room,conn); return }
    if(action==='vote'){ if(!m.isGroup) return reply('❌ Hanya di grup'); if(!room||room.state!=='DAY') return reply('🚫 Hanya siang'); let me=room.players.find(p=>p.jid===m.sender); if(!me) return reply('❌ Tidak ikut'); if(me.status==='DEAD') return reply('☠️ Mati'); if(room.votes[m.sender]) return reply('❌ Sudah vote'); let idx=parseInt(args[1])-1; let t=room.players[idx]; if(!t||t.status==='DEAD') return reply('❌ Salah'); room.votes[m.sender]=t.jid; let alive=room.players.filter(p=>p.status==='ALIVE').length, cnt=Object.keys(room.votes).length; await conn.sendMessage(m.chat,{text:`🗳️ @${m.sender.split('@')[0]} → @${t.jid.split('@')[0]} (${cnt}/${alive})`,mentions:[m.sender,t.jid]},{quoted:m}); await sendVoteSummary(room,conn); if(cnt>=alive) await resolveVote(room,conn); return }
    if(action==='stop'){ if(!m.isGroup) return reply('❌ Hanya di grup'); if(!global.werewolf[m.chat]) return reply('⚠️ Tidak ada game'); let isHost=global.werewolf[m.chat].host===m.sender, isAdmin=false; try{ let meta=await conn.groupMetadata(m.chat); isAdmin=meta.participants.find(p=>p.id===m.sender)?.admin!=null }catch{} if(!isHost&&!isAdmin) return reply('❌ Hanya host/admin'); clearNightTimer(global.werewolf[m.chat]); clearVoteTimer(global.werewolf[m.chat]); delete global.werewolf[m.chat]; return reply(`🛑 Game dihentikan`); }
    return reply(`❓ Tidak dikenal, ${pfx} help`)
}
module.exports = { handle }
